# Simple workflow for building and reporting status
name: Build and Report Status

on:
  # Runs on Pull requests
  pull_request:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        id: build
        run: npm run build